# ── BFF — SIT Environment ─────────────────────────────────────────────────────

compute:
  cpu:           256
  memory:        512
  desired_count: 1

env:
  ENV:                  sit
  LOG_LEVEL:            info
  ORDER_SERVICE_URL:    "http://localhost:8001"
  INVOICE_SERVICE_URL:  "http://localhost:8002"
  CORS_ORIGINS:         "https://d7v98dznpwca9.cloudfront.net"

env_secrets: {}
